### ISSUE TITLE
link update suggestion

### ISSUE THREAD

**Issue by neon-izm** [SnowCait/game-development-notes#1]
こんにちは！

https://github.com/SnowCait/game-development-notes/blob/master/Client.md

上の文書内の https://gist.github.com/neon-izm/7da2f6e06d10dc1f3589a5fb1fc39d27 へのリンクは https://neon-izm.github.io/before_join_socialgame/ に更新してもらえると、最新追従がしやすいかも、です！

**Comment by SnowCait** [comment]
ありがとうございます、更新しました。
綺麗なページになっててすごい！応援してます～

**Comment by SnowCait** [comment]
そしてここをリンクしてもらってる…ｗ
雑メモ程度の情報しか置いてないリポジトリなので恐縮です。（もうちょっと整理せねば）

**Comment by neon-izm** [comment]
更新ありがとうございます！サーバ側は詳しくないので勉強になります！

**Comment by neon-izm** [comment]
相互リンク！！で嬉しいです ('-'*)
